apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  labels:
    vm.name: db-vm
  name: mysql-db
  namespace: developer-utilities
spec:
  imageName: ubuntu-20-1633387172196
  className: best-effort-small
  powerState: poweredOn
  storageClass: wcpglobal-storage-profile
  networkInterfaces:
  - networkName:
    networkType: nsx-t
  vmMetadata:
      configMapName: mysql-db-cm
      transport: OvfEnv
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: mysql-db-cm
    namespace: developer-utilities
data:
  user-data: >-
    I2Nsb3VkLWNvbmZpZwoKc3NoX3B3YXV0aDogdHJ1ZQoKZ3JvdXBzOgogIC0gYWRtaW5ncm91cDogW3Jvb3Qsc3lzXQoKdXNlcnM6CiAgLSBuYW1lOiBkZXYKICAgIGdlY29zOiBEZXYgUy4gT3BzCiAgICBsb2NrX3Bhc3N3ZDogZmFsc2UKICAgIHBhc3N3ZDogJDYkcm91bmRzPTQwOTYkSmd1NnZIZ2xaeGhvdnNhZCRuTEVCNmJKRGdYMVo2d0xGNDFKbG9nNTN1bVlZSy9QUWFJdHZyNmh5Tzc0c0RTcGhrZS5PeWZXTXh0SHFlR0J2dFQuR0ZWQkl2SVFXLmthc3ZWaTJNLgogICAgc3VkbzogQUxMPShBTEwpIE5PUEFTU1dEOkFMTAogICAgZ3JvdXBzOiBzdWRvLCB1c2VycywgYWRtaW4KICAgIHNoZWxsOiAvYmluL2Jhc2gKCndyaXRlX2ZpbGVzOgogIC0gY29udGVudDogfAogICAgICAgQUxURVIgVVNFUiAncm9vdCdAJ2xvY2FsaG9zdCcgSURFTlRJRklFRCBXSVRIIG15c3FsX25hdGl2ZV9wYXNzd29yZCBCWSAncGFzc3dvcmQnOwogICAgYXBwZW5kOiB0cnVlCiAgICBwYXRoOiAvYWx0ZXJ1c2VyLnR4dAoKICAtIGNvbnRlbnQ6IHwKICAgICAgIENSRUFURSBVU0VSICdkZXZvcHMnQCclJyBJREVOVElGSUVEIEJZICdwYXNzd29yZCc7CiAgICAgICBDUkVBVEUgREFUQUJBU0UgZGVtbzsKICAgICAgIEdSQU5UIEFMTCBQUklWSUxFR0VTIE9OIGRlbW8uKiBUTyAnZGV2b3BzJ0AnJSc7CgogICAgICAgQ1JFQVRFIFRBQkxFIGRlbW8udXNlciAoCiAgICAgICAgIGlkIElOVEVHRVIgUFJJTUFSWSBLRVkgQVVUT19JTkNSRU1FTlQsCiAgICAgICAgIHVzZXJuYW1lIHZhcmNoYXIoMjU1KSBOT1QgTlVMTCwKICAgICAgICAgcGFzc3dvcmQgdmFyY2hhcigyNTUpIE5PVCBOVUxMLAogICAgICAgICBVTklRVUUgKHVzZXJuYW1lKQogICAgICAgKTsKCgogICAgICAgQ1JFQVRFIFRBQkxFIGRlbW8uZW50cnkgKAogICAgICAgICBpZCBJTlRFR0VSIFBSSU1BUlkgS0VZIEFVVE9fSU5DUkVNRU5ULAogICAgICAgICBhdXRob3JfaWQgSU5URUdFUiBOT1QgTlVMTCwKICAgICAgICAgY3JlYXRlZCBUSU1FU1RBTVAgTk9UIE5VTEwgREVGQVVMVCBDVVJSRU5UX1RJTUVTVEFNUCwKICAgICAgICAgdGl0bGUgdmFyY2hhcigyNTUpIE5PVCBOVUxMLAogICAgICAgICBib2R5IHZhcmNoYXIoNTQwMCkgTk9UIE5VTEwsCiAgICAgICAgIEZPUkVJR04gS0VZIChhdXRob3JfaWQpIFJFRkVSRU5DRVMgdXNlciAoaWQpCiAgICAgICApOwoKICAgICAgIElOU0VSVCBJTlRPIGRlbW8udXNlciAodXNlcm5hbWUscGFzc3dvcmQpIFZBTFVFUygnSmVyZW15JywnZGV2b3BzMTIzJyk7CiAgICAgICBJTlNFUlQgSU5UTyBkZW1vLmVudHJ5IChhdXRob3JfaWQsdGl0bGUsYm9keSkgVkFMVUVTKDEsIldlbGNvbWUgdG8gdGhlIHJlcXVlc3QgcGFnZSwgdGhpcyBpcyB0aGUgZmlyc3QgZW50cnkiLCJUaGlzIGVudHJ5IGlzIG93bmVkIGJ5IEplcmVteSBhbmQgY2FuIG9ubHkgYmUgbW9kaWZpZWQgYnkgaGltLiBZb3UgY2FuIGNyZWF0ZSB5b3VyIG93biBwb3N0IGJ5IHJlZ2lzdGVyaW5nIGFuZCBsb2dnaW5nIGluISIpOwogICAgYXBwZW5kOiB0cnVlCiAgICBwYXRoOiAvaW5pdC5zcWwKCnJ1bmNtZDoKICAtIHN1ZG8gYXB0IHVwZGF0ZQogIC0gc3VkbyBhcHQgLXkgaW5zdGFsbCBteXNxbC1zZXJ2ZXIKICAtIHN1ZG8gc3lzdGVtY3RsIHN0YXJ0IG15c3FsLnNlcnZpY2UKICAtIHN1ZG8gbXlzcWwgPCAvYWx0ZXJ1c2VyLnR4dAogIC0gbXlzcWwgLXUgcm9vdCAtcHBhc3N3b3JkIDwgL2luaXQuc3FsCiAgLSBzdWRvIHNlZCAtaSAnMCwvYmluZC1hZGRyZXNzL3MvLyNiaW5kLWFkZHJlc3MvJyAvZXRjL215c3FsL215c3FsLmNvbmYuZC9teXNxbGQuY25mCiAgLSBzdWRvIHN5c3RlbWN0bCByZXN0YXJ0IG15c3FsLnNlcnZpY2UKCg==
---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineService
metadata:
  name: mysql-db
  namespace: developer-utilities
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    vm.name: db-vm
  type: LoadBalancer